### PR TITLE
Deprecate Vec2 and half and introduce Vec3i

### PR DESCRIPTION
**Pull request by danrbailey**
Removed all array instantiations for half and Vec2 and introduced Vec3i (Vec2 should now use arrays of stride 2 instead)

### CODE REVIEW

**Comment by danrbailey** [comment]
@Idclip @jbrd

**Comment by Idclip** [comment]
Why are half and vec3h being deprecated?

**Comment by jbrd** [comment]
Thanks Dan. I've taken a look through this now. My only suggestion is that we follow OpenVDB in using `int32_t` rather than `int` for integer attribute arrays...

**Comment by danrbailey** [comment]
@Idclip - deprecating half in favour of using truncated float instead. Has the same storage requirements, but simplifies access because the value type is always float.
@jbrd - good point, I'll change this.

**Comment by Idclip** [comment]
@danrbailey good point, approved!

**Pull request merged**
